services:
  - name: ai-road-accident-dashboard
    type: web
    runtime: node
    plan: free
    repo: https://github.com/Kishan-Shakya/Ai-Powered_road_accident_prevention
    branch: main
    rootDir: Dashboard

    buildCommand: npm install && npm run build
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production

    autoDeployTrigger: commit
